#!/bin/sh /etc/rc.common 

START=92

USE_PROCD=1
PROG=/ugw/script/report.sh 

start_service() {
	include /lib/functions
	procd_open_instance
	procd_set_param command $PROG
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	echo "restart report"
	killstr report/main.lua
}

stop_service() {
	echo "stop report"
	killstr report/main.lua
}
